AcceleratorConfig:
  Board: pynq-z2
  Driver: python
  Interface: axi_stream
  Precision:
    Input: float
    Output: float
Backend: VivadoAccelerator
ClockPeriod: 5
HLSConfig:
  LayerName:
    conv1:
      Precision:
        bias: fixed<6,1>
        result: fixed<16,6>
        weight: fixed<6,1>
      Trace: false
    conv1_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv2:
      Precision:
        bias: fixed<6,1>
        result: fixed<16,6>
        weight: fixed<6,1>
      Trace: false
    conv2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    flatten:
      Precision:
        result: fixed<16,6>
      Trace: false
    maxpool1:
      Precision:
        result: fixed<16,6>
      Trace: false
    maxpool2:
      Precision:
        result: fixed<16,6>
      Trace: false
    output:
      Precision:
        bias: fixed<6,1>
        result: fixed<16,6>
        weight: fixed<6,1>
      Strategy: Stable
      Trace: false
    output_softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
    relu1:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
      Trace: false
    relu2:
      Precision:
        result: ufixed<6,0,RND_CONV,SAT>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 128
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
KerasModel: !keras_model 'projects/qat_hls4ml_prj/keras_model.h5'
OutputDir: projects/qat_hls4ml_prj
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: 512f2a80
Version: 1.0.0
XilinxPart: xczu5ev-sfvc784-2LV-e
