// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_logic_0 = sc_dt::Log_0;
const bool reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_boolean_1 = true;
const bool reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_boolean_0 = false;
const sc_lv<3> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv3_1 = "1";
const sc_lv<32> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv32_12 = "10010";
const sc_lv<32> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv32_11 = "10001";
const sc_lv<1> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv1_1 = "1";
const sc_lv<18> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv18_1FFFF = "11111111111111111";
const sc_lv<18> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv18_20000 = "100000000000000000";
const sc_lv<3> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv3_2 = "10";
const sc_lv<3> reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::ap_const_lv3_3 = "11";

reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_axi_mux_134_18_1_0_U1021 = new myproject_axi_mux_134_18_1_0<1,1,18,18,18,18,18,18,18,18,18,18,18,18,18,4,18>("myproject_axi_mux_134_18_1_0_U1021");
    myproject_axi_mux_134_18_1_0_U1021->din0(zext_ln43_fu_146_p1);
    myproject_axi_mux_134_18_1_0_U1021->din1(zext_ln43_3_fu_150_p1);
    myproject_axi_mux_134_18_1_0_U1021->din2(zext_ln43_4_fu_154_p1);
    myproject_axi_mux_134_18_1_0_U1021->din3(zext_ln43_5_fu_158_p1);
    myproject_axi_mux_134_18_1_0_U1021->din4(zext_ln43_6_fu_162_p1);
    myproject_axi_mux_134_18_1_0_U1021->din5(zext_ln43_7_fu_166_p1);
    myproject_axi_mux_134_18_1_0_U1021->din6(zext_ln43_8_fu_170_p1);
    myproject_axi_mux_134_18_1_0_U1021->din7(zext_ln43_9_fu_174_p1);
    myproject_axi_mux_134_18_1_0_U1021->din8(zext_ln43_10_fu_178_p1);
    myproject_axi_mux_134_18_1_0_U1021->din9(zext_ln43_11_fu_182_p1);
    myproject_axi_mux_134_18_1_0_U1021->din10(zext_ln43_12_fu_186_p1);
    myproject_axi_mux_134_18_1_0_U1021->din11(zext_ln43_13_fu_190_p1);
    myproject_axi_mux_134_18_1_0_U1021->din12(zext_ln43_14_fu_194_p1);
    myproject_axi_mux_134_18_1_0_U1021->din13(p_Val2_s_fu_198_p14);
    myproject_axi_mux_134_18_1_0_U1021->dout(p_Val2_s_fu_198_p15);
    myproject_axi_mux_134_18_1_0_U1022 = new myproject_axi_mux_134_18_1_0<1,1,18,18,18,18,18,18,18,18,18,18,18,18,18,4,18>("myproject_axi_mux_134_18_1_0_U1022");
    myproject_axi_mux_134_18_1_0_U1022->din0(zext_ln43_fu_146_p1);
    myproject_axi_mux_134_18_1_0_U1022->din1(zext_ln43_3_fu_150_p1);
    myproject_axi_mux_134_18_1_0_U1022->din2(zext_ln43_4_fu_154_p1);
    myproject_axi_mux_134_18_1_0_U1022->din3(zext_ln43_5_fu_158_p1);
    myproject_axi_mux_134_18_1_0_U1022->din4(zext_ln43_6_fu_162_p1);
    myproject_axi_mux_134_18_1_0_U1022->din5(zext_ln43_7_fu_166_p1);
    myproject_axi_mux_134_18_1_0_U1022->din6(zext_ln43_8_fu_170_p1);
    myproject_axi_mux_134_18_1_0_U1022->din7(zext_ln43_9_fu_174_p1);
    myproject_axi_mux_134_18_1_0_U1022->din8(zext_ln43_10_fu_178_p1);
    myproject_axi_mux_134_18_1_0_U1022->din9(zext_ln43_11_fu_182_p1);
    myproject_axi_mux_134_18_1_0_U1022->din10(zext_ln43_12_fu_186_p1);
    myproject_axi_mux_134_18_1_0_U1022->din11(zext_ln43_13_fu_190_p1);
    myproject_axi_mux_134_18_1_0_U1022->din12(zext_ln43_14_fu_194_p1);
    myproject_axi_mux_134_18_1_0_U1022->din13(p_Val2_46_fu_240_p14);
    myproject_axi_mux_134_18_1_0_U1022->dout(p_Val2_46_fu_240_p15);
    myproject_axi_mux_134_18_1_0_U1023 = new myproject_axi_mux_134_18_1_0<1,1,18,18,18,18,18,18,18,18,18,18,18,18,18,4,18>("myproject_axi_mux_134_18_1_0_U1023");
    myproject_axi_mux_134_18_1_0_U1023->din0(zext_ln43_fu_146_p1);
    myproject_axi_mux_134_18_1_0_U1023->din1(zext_ln43_3_fu_150_p1);
    myproject_axi_mux_134_18_1_0_U1023->din2(zext_ln43_4_fu_154_p1);
    myproject_axi_mux_134_18_1_0_U1023->din3(zext_ln43_5_fu_158_p1);
    myproject_axi_mux_134_18_1_0_U1023->din4(zext_ln43_6_fu_162_p1);
    myproject_axi_mux_134_18_1_0_U1023->din5(zext_ln43_7_fu_166_p1);
    myproject_axi_mux_134_18_1_0_U1023->din6(zext_ln43_8_fu_170_p1);
    myproject_axi_mux_134_18_1_0_U1023->din7(zext_ln43_9_fu_174_p1);
    myproject_axi_mux_134_18_1_0_U1023->din8(zext_ln43_10_fu_178_p1);
    myproject_axi_mux_134_18_1_0_U1023->din9(zext_ln43_11_fu_182_p1);
    myproject_axi_mux_134_18_1_0_U1023->din10(zext_ln43_12_fu_186_p1);
    myproject_axi_mux_134_18_1_0_U1023->din11(zext_ln43_13_fu_190_p1);
    myproject_axi_mux_134_18_1_0_U1023->din12(zext_ln43_14_fu_194_p1);
    myproject_axi_mux_134_18_1_0_U1023->din13(p_Val2_49_fu_372_p14);
    myproject_axi_mux_134_18_1_0_U1023->dout(p_Val2_49_fu_372_p15);
    myproject_axi_mux_134_18_1_0_U1024 = new myproject_axi_mux_134_18_1_0<1,1,18,18,18,18,18,18,18,18,18,18,18,18,18,4,18>("myproject_axi_mux_134_18_1_0_U1024");
    myproject_axi_mux_134_18_1_0_U1024->din0(zext_ln43_fu_146_p1);
    myproject_axi_mux_134_18_1_0_U1024->din1(zext_ln43_3_fu_150_p1);
    myproject_axi_mux_134_18_1_0_U1024->din2(zext_ln43_4_fu_154_p1);
    myproject_axi_mux_134_18_1_0_U1024->din3(zext_ln43_5_fu_158_p1);
    myproject_axi_mux_134_18_1_0_U1024->din4(zext_ln43_6_fu_162_p1);
    myproject_axi_mux_134_18_1_0_U1024->din5(zext_ln43_7_fu_166_p1);
    myproject_axi_mux_134_18_1_0_U1024->din6(zext_ln43_8_fu_170_p1);
    myproject_axi_mux_134_18_1_0_U1024->din7(zext_ln43_9_fu_174_p1);
    myproject_axi_mux_134_18_1_0_U1024->din8(zext_ln43_10_fu_178_p1);
    myproject_axi_mux_134_18_1_0_U1024->din9(zext_ln43_11_fu_182_p1);
    myproject_axi_mux_134_18_1_0_U1024->din10(zext_ln43_12_fu_186_p1);
    myproject_axi_mux_134_18_1_0_U1024->din11(zext_ln43_13_fu_190_p1);
    myproject_axi_mux_134_18_1_0_U1024->din12(zext_ln43_14_fu_194_p1);
    myproject_axi_mux_134_18_1_0_U1024->din13(p_Val2_2_fu_414_p14);
    myproject_axi_mux_134_18_1_0_U1024->dout(p_Val2_2_fu_414_p15);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln43_1_fu_404_p2);
    sensitive << ( empty_fu_138_p1 );

    SC_METHOD(thread_add_ln43_fu_230_p2);
    sensitive << ( empty_fu_138_p1 );

    SC_METHOD(thread_add_ln45_fu_362_p2);
    sensitive << ( empty_fu_138_p1 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return);
    sensitive << ( select_ln340_38_fu_610_p3 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_int_reg );

    SC_METHOD(thread_empty_fu_138_p1);
    sensitive << ( x_V_offset );

    SC_METHOD(thread_lhs_V_3_fu_272_p1);
    sensitive << ( p_Val2_s_fu_198_p15 );

    SC_METHOD(thread_lhs_V_4_fu_446_p1);
    sensitive << ( p_Val2_49_fu_372_p15 );

    SC_METHOD(thread_lhs_V_fu_536_p1);
    sensitive << ( p_Val2_52_fu_354_p3 );

    SC_METHOD(thread_or_ln340_16_fu_332_p2);
    sensitive << ( p_Result_28_fu_300_p3 );
    sensitive << ( xor_ln340_33_fu_326_p2 );

    SC_METHOD(thread_or_ln340_17_fu_506_p2);
    sensitive << ( p_Result_30_fu_474_p3 );
    sensitive << ( xor_ln340_35_fu_500_p2 );

    SC_METHOD(thread_or_ln340_fu_591_p2);
    sensitive << ( p_Result_32_reg_631 );
    sensitive << ( xor_ln340_fu_586_p2 );

    SC_METHOD(thread_p_Result_28_fu_300_p3);
    sensitive << ( p_Val2_48_fu_294_p2 );

    SC_METHOD(thread_p_Result_29_fu_460_p3);
    sensitive << ( ret_V_3_fu_454_p2 );

    SC_METHOD(thread_p_Result_30_fu_474_p3);
    sensitive << ( p_Val2_51_fu_468_p2 );

    SC_METHOD(thread_p_Result_s_fu_286_p3);
    sensitive << ( ret_V_fu_280_p2 );

    SC_METHOD(thread_p_Val2_2_fu_414_p14);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( add_ln43_1_fu_404_p2 );

    SC_METHOD(thread_p_Val2_46_fu_240_p14);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( add_ln43_fu_230_p2 );

    SC_METHOD(thread_p_Val2_48_fu_294_p2);
    sensitive << ( p_Val2_s_fu_198_p15 );
    sensitive << ( p_Val2_46_fu_240_p15 );

    SC_METHOD(thread_p_Val2_49_fu_372_p14);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( add_ln45_fu_362_p2 );

    SC_METHOD(thread_p_Val2_51_fu_468_p2);
    sensitive << ( p_Val2_49_fu_372_p15 );
    sensitive << ( p_Val2_2_fu_414_p15 );

    SC_METHOD(thread_p_Val2_52_fu_354_p3);
    sensitive << ( or_ln340_16_fu_332_p2 );
    sensitive << ( select_ln340_34_fu_338_p3 );
    sensitive << ( select_ln388_15_fu_346_p3 );

    SC_METHOD(thread_p_Val2_53_fu_528_p3);
    sensitive << ( or_ln340_17_fu_506_p2 );
    sensitive << ( select_ln340_36_fu_512_p3 );
    sensitive << ( select_ln388_16_fu_520_p3 );

    SC_METHOD(thread_p_Val2_55_fu_558_p2);
    sensitive << ( p_Val2_52_fu_354_p3 );
    sensitive << ( p_Val2_53_fu_528_p3 );

    SC_METHOD(thread_p_Val2_s_fu_198_p14);
    sensitive << ( x_V_offset );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ret_V_3_fu_454_p2);
    sensitive << ( rhs_V_4_fu_450_p1 );
    sensitive << ( lhs_V_4_fu_446_p1 );

    SC_METHOD(thread_ret_V_4_fu_544_p2);
    sensitive << ( lhs_V_fu_536_p1 );
    sensitive << ( rhs_V_fu_540_p1 );

    SC_METHOD(thread_ret_V_fu_280_p2);
    sensitive << ( rhs_V_3_fu_276_p1 );
    sensitive << ( lhs_V_3_fu_272_p1 );

    SC_METHOD(thread_rhs_V_3_fu_276_p1);
    sensitive << ( p_Val2_46_fu_240_p15 );

    SC_METHOD(thread_rhs_V_4_fu_450_p1);
    sensitive << ( p_Val2_2_fu_414_p15 );

    SC_METHOD(thread_rhs_V_fu_540_p1);
    sensitive << ( p_Val2_53_fu_528_p3 );

    SC_METHOD(thread_select_ln340_34_fu_338_p3);
    sensitive << ( p_Val2_48_fu_294_p2 );
    sensitive << ( xor_ln340_32_fu_320_p2 );

    SC_METHOD(thread_select_ln340_36_fu_512_p3);
    sensitive << ( p_Val2_51_fu_468_p2 );
    sensitive << ( xor_ln340_34_fu_494_p2 );

    SC_METHOD(thread_select_ln340_38_fu_610_p3);
    sensitive << ( or_ln340_fu_591_p2 );
    sensitive << ( select_ln340_fu_596_p3 );
    sensitive << ( select_ln388_fu_603_p3 );

    SC_METHOD(thread_select_ln340_fu_596_p3);
    sensitive << ( p_Val2_55_reg_625 );
    sensitive << ( xor_ln340_36_fu_582_p2 );

    SC_METHOD(thread_select_ln388_15_fu_346_p3);
    sensitive << ( p_Val2_48_fu_294_p2 );
    sensitive << ( underflow_fu_314_p2 );

    SC_METHOD(thread_select_ln388_16_fu_520_p3);
    sensitive << ( p_Val2_51_fu_468_p2 );
    sensitive << ( underflow_3_fu_488_p2 );

    SC_METHOD(thread_select_ln388_fu_603_p3);
    sensitive << ( p_Val2_55_reg_625 );
    sensitive << ( underflow_4_fu_577_p2 );

    SC_METHOD(thread_underflow_3_fu_488_p2);
    sensitive << ( p_Result_29_fu_460_p3 );
    sensitive << ( xor_ln786_16_fu_482_p2 );

    SC_METHOD(thread_underflow_4_fu_577_p2);
    sensitive << ( p_Result_31_reg_618 );
    sensitive << ( xor_ln786_fu_572_p2 );

    SC_METHOD(thread_underflow_fu_314_p2);
    sensitive << ( p_Result_s_fu_286_p3 );
    sensitive << ( xor_ln786_15_fu_308_p2 );

    SC_METHOD(thread_xor_ln340_32_fu_320_p2);
    sensitive << ( p_Result_28_fu_300_p3 );
    sensitive << ( p_Result_s_fu_286_p3 );

    SC_METHOD(thread_xor_ln340_33_fu_326_p2);
    sensitive << ( p_Result_s_fu_286_p3 );

    SC_METHOD(thread_xor_ln340_34_fu_494_p2);
    sensitive << ( p_Result_30_fu_474_p3 );
    sensitive << ( p_Result_29_fu_460_p3 );

    SC_METHOD(thread_xor_ln340_35_fu_500_p2);
    sensitive << ( p_Result_29_fu_460_p3 );

    SC_METHOD(thread_xor_ln340_36_fu_582_p2);
    sensitive << ( p_Result_31_reg_618 );
    sensitive << ( p_Result_32_reg_631 );

    SC_METHOD(thread_xor_ln340_fu_586_p2);
    sensitive << ( p_Result_31_reg_618 );

    SC_METHOD(thread_xor_ln786_15_fu_308_p2);
    sensitive << ( p_Result_28_fu_300_p3 );

    SC_METHOD(thread_xor_ln786_16_fu_482_p2);
    sensitive << ( p_Result_30_fu_474_p3 );

    SC_METHOD(thread_xor_ln786_fu_572_p2);
    sensitive << ( p_Result_32_reg_631 );

    SC_METHOD(thread_zext_ln43_10_fu_178_p1);
    sensitive << ( x_8_V );

    SC_METHOD(thread_zext_ln43_11_fu_182_p1);
    sensitive << ( x_9_V );

    SC_METHOD(thread_zext_ln43_12_fu_186_p1);
    sensitive << ( x_10_V );

    SC_METHOD(thread_zext_ln43_13_fu_190_p1);
    sensitive << ( x_11_V );

    SC_METHOD(thread_zext_ln43_14_fu_194_p1);
    sensitive << ( x_12_V );

    SC_METHOD(thread_zext_ln43_3_fu_150_p1);
    sensitive << ( x_1_V );

    SC_METHOD(thread_zext_ln43_4_fu_154_p1);
    sensitive << ( x_2_V );

    SC_METHOD(thread_zext_ln43_5_fu_158_p1);
    sensitive << ( x_3_V );

    SC_METHOD(thread_zext_ln43_6_fu_162_p1);
    sensitive << ( x_4_V );

    SC_METHOD(thread_zext_ln43_7_fu_166_p1);
    sensitive << ( x_5_V );

    SC_METHOD(thread_zext_ln43_8_fu_170_p1);
    sensitive << ( x_6_V );

    SC_METHOD(thread_zext_ln43_9_fu_174_p1);
    sensitive << ( x_7_V );

    SC_METHOD(thread_zext_ln43_fu_146_p1);
    sensitive << ( x_0_V );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, x_0_V, "(port)x_0_V");
    sc_trace(mVcdFile, x_1_V, "(port)x_1_V");
    sc_trace(mVcdFile, x_2_V, "(port)x_2_V");
    sc_trace(mVcdFile, x_3_V, "(port)x_3_V");
    sc_trace(mVcdFile, x_4_V, "(port)x_4_V");
    sc_trace(mVcdFile, x_5_V, "(port)x_5_V");
    sc_trace(mVcdFile, x_6_V, "(port)x_6_V");
    sc_trace(mVcdFile, x_7_V, "(port)x_7_V");
    sc_trace(mVcdFile, x_8_V, "(port)x_8_V");
    sc_trace(mVcdFile, x_9_V, "(port)x_9_V");
    sc_trace(mVcdFile, x_10_V, "(port)x_10_V");
    sc_trace(mVcdFile, x_11_V, "(port)x_11_V");
    sc_trace(mVcdFile, x_12_V, "(port)x_12_V");
    sc_trace(mVcdFile, x_V_offset, "(port)x_V_offset");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, p_Result_31_reg_618, "p_Result_31_reg_618");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, p_Val2_55_fu_558_p2, "p_Val2_55_fu_558_p2");
    sc_trace(mVcdFile, p_Val2_55_reg_625, "p_Val2_55_reg_625");
    sc_trace(mVcdFile, p_Result_32_reg_631, "p_Result_32_reg_631");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln43_fu_146_p1, "zext_ln43_fu_146_p1");
    sc_trace(mVcdFile, zext_ln43_3_fu_150_p1, "zext_ln43_3_fu_150_p1");
    sc_trace(mVcdFile, zext_ln43_4_fu_154_p1, "zext_ln43_4_fu_154_p1");
    sc_trace(mVcdFile, zext_ln43_5_fu_158_p1, "zext_ln43_5_fu_158_p1");
    sc_trace(mVcdFile, zext_ln43_6_fu_162_p1, "zext_ln43_6_fu_162_p1");
    sc_trace(mVcdFile, zext_ln43_7_fu_166_p1, "zext_ln43_7_fu_166_p1");
    sc_trace(mVcdFile, zext_ln43_8_fu_170_p1, "zext_ln43_8_fu_170_p1");
    sc_trace(mVcdFile, zext_ln43_9_fu_174_p1, "zext_ln43_9_fu_174_p1");
    sc_trace(mVcdFile, zext_ln43_10_fu_178_p1, "zext_ln43_10_fu_178_p1");
    sc_trace(mVcdFile, zext_ln43_11_fu_182_p1, "zext_ln43_11_fu_182_p1");
    sc_trace(mVcdFile, zext_ln43_12_fu_186_p1, "zext_ln43_12_fu_186_p1");
    sc_trace(mVcdFile, zext_ln43_13_fu_190_p1, "zext_ln43_13_fu_190_p1");
    sc_trace(mVcdFile, zext_ln43_14_fu_194_p1, "zext_ln43_14_fu_194_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_198_p14, "p_Val2_s_fu_198_p14");
    sc_trace(mVcdFile, empty_fu_138_p1, "empty_fu_138_p1");
    sc_trace(mVcdFile, add_ln43_fu_230_p2, "add_ln43_fu_230_p2");
    sc_trace(mVcdFile, p_Val2_46_fu_240_p14, "p_Val2_46_fu_240_p14");
    sc_trace(mVcdFile, p_Val2_s_fu_198_p15, "p_Val2_s_fu_198_p15");
    sc_trace(mVcdFile, p_Val2_46_fu_240_p15, "p_Val2_46_fu_240_p15");
    sc_trace(mVcdFile, rhs_V_3_fu_276_p1, "rhs_V_3_fu_276_p1");
    sc_trace(mVcdFile, lhs_V_3_fu_272_p1, "lhs_V_3_fu_272_p1");
    sc_trace(mVcdFile, ret_V_fu_280_p2, "ret_V_fu_280_p2");
    sc_trace(mVcdFile, p_Val2_48_fu_294_p2, "p_Val2_48_fu_294_p2");
    sc_trace(mVcdFile, p_Result_28_fu_300_p3, "p_Result_28_fu_300_p3");
    sc_trace(mVcdFile, p_Result_s_fu_286_p3, "p_Result_s_fu_286_p3");
    sc_trace(mVcdFile, xor_ln786_15_fu_308_p2, "xor_ln786_15_fu_308_p2");
    sc_trace(mVcdFile, xor_ln340_33_fu_326_p2, "xor_ln340_33_fu_326_p2");
    sc_trace(mVcdFile, xor_ln340_32_fu_320_p2, "xor_ln340_32_fu_320_p2");
    sc_trace(mVcdFile, underflow_fu_314_p2, "underflow_fu_314_p2");
    sc_trace(mVcdFile, or_ln340_16_fu_332_p2, "or_ln340_16_fu_332_p2");
    sc_trace(mVcdFile, select_ln340_34_fu_338_p3, "select_ln340_34_fu_338_p3");
    sc_trace(mVcdFile, select_ln388_15_fu_346_p3, "select_ln388_15_fu_346_p3");
    sc_trace(mVcdFile, add_ln45_fu_362_p2, "add_ln45_fu_362_p2");
    sc_trace(mVcdFile, p_Val2_49_fu_372_p14, "p_Val2_49_fu_372_p14");
    sc_trace(mVcdFile, add_ln43_1_fu_404_p2, "add_ln43_1_fu_404_p2");
    sc_trace(mVcdFile, p_Val2_2_fu_414_p14, "p_Val2_2_fu_414_p14");
    sc_trace(mVcdFile, p_Val2_49_fu_372_p15, "p_Val2_49_fu_372_p15");
    sc_trace(mVcdFile, p_Val2_2_fu_414_p15, "p_Val2_2_fu_414_p15");
    sc_trace(mVcdFile, rhs_V_4_fu_450_p1, "rhs_V_4_fu_450_p1");
    sc_trace(mVcdFile, lhs_V_4_fu_446_p1, "lhs_V_4_fu_446_p1");
    sc_trace(mVcdFile, ret_V_3_fu_454_p2, "ret_V_3_fu_454_p2");
    sc_trace(mVcdFile, p_Val2_51_fu_468_p2, "p_Val2_51_fu_468_p2");
    sc_trace(mVcdFile, p_Result_30_fu_474_p3, "p_Result_30_fu_474_p3");
    sc_trace(mVcdFile, p_Result_29_fu_460_p3, "p_Result_29_fu_460_p3");
    sc_trace(mVcdFile, xor_ln786_16_fu_482_p2, "xor_ln786_16_fu_482_p2");
    sc_trace(mVcdFile, xor_ln340_35_fu_500_p2, "xor_ln340_35_fu_500_p2");
    sc_trace(mVcdFile, xor_ln340_34_fu_494_p2, "xor_ln340_34_fu_494_p2");
    sc_trace(mVcdFile, underflow_3_fu_488_p2, "underflow_3_fu_488_p2");
    sc_trace(mVcdFile, or_ln340_17_fu_506_p2, "or_ln340_17_fu_506_p2");
    sc_trace(mVcdFile, select_ln340_36_fu_512_p3, "select_ln340_36_fu_512_p3");
    sc_trace(mVcdFile, select_ln388_16_fu_520_p3, "select_ln388_16_fu_520_p3");
    sc_trace(mVcdFile, p_Val2_52_fu_354_p3, "p_Val2_52_fu_354_p3");
    sc_trace(mVcdFile, p_Val2_53_fu_528_p3, "p_Val2_53_fu_528_p3");
    sc_trace(mVcdFile, lhs_V_fu_536_p1, "lhs_V_fu_536_p1");
    sc_trace(mVcdFile, rhs_V_fu_540_p1, "rhs_V_fu_540_p1");
    sc_trace(mVcdFile, ret_V_4_fu_544_p2, "ret_V_4_fu_544_p2");
    sc_trace(mVcdFile, xor_ln786_fu_572_p2, "xor_ln786_fu_572_p2");
    sc_trace(mVcdFile, xor_ln340_fu_586_p2, "xor_ln340_fu_586_p2");
    sc_trace(mVcdFile, xor_ln340_36_fu_582_p2, "xor_ln340_36_fu_582_p2");
    sc_trace(mVcdFile, underflow_4_fu_577_p2, "underflow_4_fu_577_p2");
    sc_trace(mVcdFile, or_ln340_fu_591_p2, "or_ln340_fu_591_p2");
    sc_trace(mVcdFile, select_ln340_fu_596_p3, "select_ln340_fu_596_p3");
    sc_trace(mVcdFile, select_ln388_fu_603_p3, "select_ln388_fu_603_p3");
    sc_trace(mVcdFile, select_ln340_38_fu_610_p3, "select_ln340_38_fu_610_p3");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, ap_return_int_reg, "ap_return_int_reg");
#endif

    }
}

reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::~reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_axi_mux_134_18_1_0_U1021;
    delete myproject_axi_mux_134_18_1_0_U1022;
    delete myproject_axi_mux_134_18_1_0_U1023;
    delete myproject_axi_mux_134_18_1_0_U1024;
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_int_reg = select_ln340_38_fu_610_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        p_Result_31_reg_618 = ret_V_4_fu_544_p2.read().range(18, 18);
        p_Result_32_reg_631 = p_Val2_55_fu_558_p2.read().range(17, 17);
        p_Val2_55_reg_625 = p_Val2_55_fu_558_p2.read();
    }
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_add_ln43_1_fu_404_p2() {
    add_ln43_1_fu_404_p2 = (!ap_const_lv3_3.is_01() || !empty_fu_138_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_3) + sc_biguint<3>(empty_fu_138_p1.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_add_ln43_fu_230_p2() {
    add_ln43_fu_230_p2 = (!ap_const_lv3_1.is_01() || !empty_fu_138_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(empty_fu_138_p1.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_add_ln45_fu_362_p2() {
    add_ln45_fu_362_p2 = (!ap_const_lv3_2.is_01() || !empty_fu_138_p1.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_2) + sc_biguint<3>(empty_fu_138_p1.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return = ap_return_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return = select_ln340_38_fu_610_p3.read();
    }
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_empty_fu_138_p1() {
    empty_fu_138_p1 = x_V_offset.read().range(3-1, 0);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_lhs_V_3_fu_272_p1() {
    lhs_V_3_fu_272_p1 = esl_sext<19,18>(p_Val2_s_fu_198_p15.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_lhs_V_4_fu_446_p1() {
    lhs_V_4_fu_446_p1 = esl_sext<19,18>(p_Val2_49_fu_372_p15.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_lhs_V_fu_536_p1() {
    lhs_V_fu_536_p1 = esl_sext<19,18>(p_Val2_52_fu_354_p3.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_or_ln340_16_fu_332_p2() {
    or_ln340_16_fu_332_p2 = (p_Result_28_fu_300_p3.read() | xor_ln340_33_fu_326_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_or_ln340_17_fu_506_p2() {
    or_ln340_17_fu_506_p2 = (p_Result_30_fu_474_p3.read() | xor_ln340_35_fu_500_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_or_ln340_fu_591_p2() {
    or_ln340_fu_591_p2 = (p_Result_32_reg_631.read() | xor_ln340_fu_586_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Result_28_fu_300_p3() {
    p_Result_28_fu_300_p3 = p_Val2_48_fu_294_p2.read().range(17, 17);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Result_29_fu_460_p3() {
    p_Result_29_fu_460_p3 = ret_V_3_fu_454_p2.read().range(18, 18);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Result_30_fu_474_p3() {
    p_Result_30_fu_474_p3 = p_Val2_51_fu_468_p2.read().range(17, 17);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Result_s_fu_286_p3() {
    p_Result_s_fu_286_p3 = ret_V_fu_280_p2.read().range(18, 18);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_2_fu_414_p14() {
    p_Val2_2_fu_414_p14 = esl_zext<4,3>(add_ln43_1_fu_404_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_46_fu_240_p14() {
    p_Val2_46_fu_240_p14 = esl_zext<4,3>(add_ln43_fu_230_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_48_fu_294_p2() {
    p_Val2_48_fu_294_p2 = (!p_Val2_s_fu_198_p15.read().is_01() || !p_Val2_46_fu_240_p15.read().is_01())? sc_lv<18>(): (sc_bigint<18>(p_Val2_s_fu_198_p15.read()) + sc_bigint<18>(p_Val2_46_fu_240_p15.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_49_fu_372_p14() {
    p_Val2_49_fu_372_p14 = esl_zext<4,3>(add_ln45_fu_362_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_51_fu_468_p2() {
    p_Val2_51_fu_468_p2 = (!p_Val2_49_fu_372_p15.read().is_01() || !p_Val2_2_fu_414_p15.read().is_01())? sc_lv<18>(): (sc_bigint<18>(p_Val2_49_fu_372_p15.read()) + sc_bigint<18>(p_Val2_2_fu_414_p15.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_52_fu_354_p3() {
    p_Val2_52_fu_354_p3 = (!or_ln340_16_fu_332_p2.read()[0].is_01())? sc_lv<18>(): ((or_ln340_16_fu_332_p2.read()[0].to_bool())? select_ln340_34_fu_338_p3.read(): select_ln388_15_fu_346_p3.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_53_fu_528_p3() {
    p_Val2_53_fu_528_p3 = (!or_ln340_17_fu_506_p2.read()[0].is_01())? sc_lv<18>(): ((or_ln340_17_fu_506_p2.read()[0].to_bool())? select_ln340_36_fu_512_p3.read(): select_ln388_16_fu_520_p3.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_55_fu_558_p2() {
    p_Val2_55_fu_558_p2 = (!p_Val2_53_fu_528_p3.read().is_01() || !p_Val2_52_fu_354_p3.read().is_01())? sc_lv<18>(): (sc_bigint<18>(p_Val2_53_fu_528_p3.read()) + sc_bigint<18>(p_Val2_52_fu_354_p3.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_p_Val2_s_fu_198_p14() {
    p_Val2_s_fu_198_p14 = x_V_offset.read().range(4-1, 0);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ret_V_3_fu_454_p2() {
    ret_V_3_fu_454_p2 = (!rhs_V_4_fu_450_p1.read().is_01() || !lhs_V_4_fu_446_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(rhs_V_4_fu_450_p1.read()) + sc_bigint<19>(lhs_V_4_fu_446_p1.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ret_V_4_fu_544_p2() {
    ret_V_4_fu_544_p2 = (!lhs_V_fu_536_p1.read().is_01() || !rhs_V_fu_540_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(lhs_V_fu_536_p1.read()) + sc_bigint<19>(rhs_V_fu_540_p1.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_ret_V_fu_280_p2() {
    ret_V_fu_280_p2 = (!rhs_V_3_fu_276_p1.read().is_01() || !lhs_V_3_fu_272_p1.read().is_01())? sc_lv<19>(): (sc_bigint<19>(rhs_V_3_fu_276_p1.read()) + sc_bigint<19>(lhs_V_3_fu_272_p1.read()));
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_rhs_V_3_fu_276_p1() {
    rhs_V_3_fu_276_p1 = esl_sext<19,18>(p_Val2_46_fu_240_p15.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_rhs_V_4_fu_450_p1() {
    rhs_V_4_fu_450_p1 = esl_sext<19,18>(p_Val2_2_fu_414_p15.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_rhs_V_fu_540_p1() {
    rhs_V_fu_540_p1 = esl_sext<19,18>(p_Val2_53_fu_528_p3.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_select_ln340_34_fu_338_p3() {
    select_ln340_34_fu_338_p3 = (!xor_ln340_32_fu_320_p2.read()[0].is_01())? sc_lv<18>(): ((xor_ln340_32_fu_320_p2.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_48_fu_294_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_select_ln340_36_fu_512_p3() {
    select_ln340_36_fu_512_p3 = (!xor_ln340_34_fu_494_p2.read()[0].is_01())? sc_lv<18>(): ((xor_ln340_34_fu_494_p2.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_51_fu_468_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_select_ln340_38_fu_610_p3() {
    select_ln340_38_fu_610_p3 = (!or_ln340_fu_591_p2.read()[0].is_01())? sc_lv<18>(): ((or_ln340_fu_591_p2.read()[0].to_bool())? select_ln340_fu_596_p3.read(): select_ln388_fu_603_p3.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_select_ln340_fu_596_p3() {
    select_ln340_fu_596_p3 = (!xor_ln340_36_fu_582_p2.read()[0].is_01())? sc_lv<18>(): ((xor_ln340_36_fu_582_p2.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_55_reg_625.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_select_ln388_15_fu_346_p3() {
    select_ln388_15_fu_346_p3 = (!underflow_fu_314_p2.read()[0].is_01())? sc_lv<18>(): ((underflow_fu_314_p2.read()[0].to_bool())? ap_const_lv18_20000: p_Val2_48_fu_294_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_select_ln388_16_fu_520_p3() {
    select_ln388_16_fu_520_p3 = (!underflow_3_fu_488_p2.read()[0].is_01())? sc_lv<18>(): ((underflow_3_fu_488_p2.read()[0].to_bool())? ap_const_lv18_20000: p_Val2_51_fu_468_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_select_ln388_fu_603_p3() {
    select_ln388_fu_603_p3 = (!underflow_4_fu_577_p2.read()[0].is_01())? sc_lv<18>(): ((underflow_4_fu_577_p2.read()[0].to_bool())? ap_const_lv18_20000: p_Val2_55_reg_625.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_underflow_3_fu_488_p2() {
    underflow_3_fu_488_p2 = (p_Result_29_fu_460_p3.read() & xor_ln786_16_fu_482_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_underflow_4_fu_577_p2() {
    underflow_4_fu_577_p2 = (p_Result_31_reg_618.read() & xor_ln786_fu_572_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_underflow_fu_314_p2() {
    underflow_fu_314_p2 = (p_Result_s_fu_286_p3.read() & xor_ln786_15_fu_308_p2.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln340_32_fu_320_p2() {
    xor_ln340_32_fu_320_p2 = (p_Result_s_fu_286_p3.read() ^ p_Result_28_fu_300_p3.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln340_33_fu_326_p2() {
    xor_ln340_33_fu_326_p2 = (p_Result_s_fu_286_p3.read() ^ ap_const_lv1_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln340_34_fu_494_p2() {
    xor_ln340_34_fu_494_p2 = (p_Result_29_fu_460_p3.read() ^ p_Result_30_fu_474_p3.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln340_35_fu_500_p2() {
    xor_ln340_35_fu_500_p2 = (p_Result_29_fu_460_p3.read() ^ ap_const_lv1_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln340_36_fu_582_p2() {
    xor_ln340_36_fu_582_p2 = (p_Result_31_reg_618.read() ^ p_Result_32_reg_631.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln340_fu_586_p2() {
    xor_ln340_fu_586_p2 = (p_Result_31_reg_618.read() ^ ap_const_lv1_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln786_15_fu_308_p2() {
    xor_ln786_15_fu_308_p2 = (p_Result_28_fu_300_p3.read() ^ ap_const_lv1_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln786_16_fu_482_p2() {
    xor_ln786_16_fu_482_p2 = (p_Result_30_fu_474_p3.read() ^ ap_const_lv1_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_xor_ln786_fu_572_p2() {
    xor_ln786_fu_572_p2 = (p_Result_32_reg_631.read() ^ ap_const_lv1_1);
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_10_fu_178_p1() {
    zext_ln43_10_fu_178_p1 = esl_zext<18,17>(x_8_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_11_fu_182_p1() {
    zext_ln43_11_fu_182_p1 = esl_zext<18,17>(x_9_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_12_fu_186_p1() {
    zext_ln43_12_fu_186_p1 = esl_zext<18,17>(x_10_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_13_fu_190_p1() {
    zext_ln43_13_fu_190_p1 = esl_zext<18,17>(x_11_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_14_fu_194_p1() {
    zext_ln43_14_fu_194_p1 = esl_zext<18,17>(x_12_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_3_fu_150_p1() {
    zext_ln43_3_fu_150_p1 = esl_zext<18,17>(x_1_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_4_fu_154_p1() {
    zext_ln43_4_fu_154_p1 = esl_zext<18,17>(x_2_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_5_fu_158_p1() {
    zext_ln43_5_fu_158_p1 = esl_zext<18,17>(x_3_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_6_fu_162_p1() {
    zext_ln43_6_fu_162_p1 = esl_zext<18,17>(x_4_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_7_fu_166_p1() {
    zext_ln43_7_fu_166_p1 = esl_zext<18,17>(x_5_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_8_fu_170_p1() {
    zext_ln43_8_fu_170_p1 = esl_zext<18,17>(x_6_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_9_fu_174_p1() {
    zext_ln43_9_fu_174_p1 = esl_zext<18,17>(x_7_V.read());
}

void reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s::thread_zext_ln43_fu_146_p1() {
    zext_ln43_fu_146_p1 = esl_zext<18,17>(x_0_V.read());
}

}

