-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Loop_2_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_TVALID : OUT STD_LOGIC;
    out_r_TREADY : IN STD_LOGIC;
    out_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_read : IN STD_LOGIC_VECTOR (0 downto 0);
    tmp_data_V_0 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_2 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_3 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_4 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_5 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_6 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_727 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_data_V_12 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of Loop_2_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv32_FFFFFFE8 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111101000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_FFFFFFE7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111100111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv16_FFE8 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111101000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal out_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal j_fu_235_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_580 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal regslice_both_out_data_U_apdone_blk : STD_LOGIC;
    signal last_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_reg_585 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_3_fu_252_p15 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_3_reg_590 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_39_reg_597 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_fu_292_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_reg_603 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln935_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln935_reg_608 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_V_4_fu_302_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_4_reg_613 : STD_LOGIC_VECTOR (15 downto 0);
    signal l_fu_325_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_reg_621 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln943_fu_333_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln943_reg_626 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln944_fu_337_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln944_reg_631 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln944_fu_342_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln944_reg_638 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln947_fu_350_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln947_reg_643 : STD_LOGIC_VECTOR (4 downto 0);
    signal lsb_index_fu_356_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lsb_index_reg_648 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_reg_654 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln947_1_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln947_1_reg_659 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln958_fu_391_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln958_reg_664 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln958_fu_396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln958_reg_669 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_i_fu_448_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_i_reg_674 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln958_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln958_reg_689 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_467_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln958_reg_699 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_475_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln958_reg_704 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_5_reg_709 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_94_reg_714 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln964_fu_517_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln964_reg_719 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal j3_0_i_reg_218 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln32_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_307_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_40_fu_317_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln947_fu_346_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln947_fu_371_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln947_fu_374_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_35_fu_380_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln947_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_93_fu_411_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln949_fu_424_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_37_fu_429_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln949_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln949_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln949_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_467_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_475_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_475_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln958_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln961_fu_490_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_1_fu_484_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal m_2_fu_493_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln964_fu_527_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln964_fu_532_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal m_6_fu_524_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_93_i_fu_537_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_41_fu_544_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln738_fu_556_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln739_fu_560_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal out_r_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_TVALID_int : STD_LOGIC;
    signal out_r_TREADY_int : STD_LOGIC;
    signal regslice_both_out_data_U_vld_out : STD_LOGIC;
    signal regslice_both_out_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_last_V_U_vld_out : STD_LOGIC;

    component myproject_axi_mux_134_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        din8 : IN STD_LOGIC_VECTOR (15 downto 0);
        din9 : IN STD_LOGIC_VECTOR (15 downto 0);
        din10 : IN STD_LOGIC_VECTOR (15 downto 0);
        din11 : IN STD_LOGIC_VECTOR (15 downto 0);
        din12 : IN STD_LOGIC_VECTOR (15 downto 0);
        din13 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_axi_lshr_32ns_32ns_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        OP : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myproject_axi_shl_64ns_32ns_64_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        OP : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    myproject_axi_mux_134_16_1_1_U1193 : component myproject_axi_mux_134_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 16,
        din6_WIDTH => 16,
        din7_WIDTH => 16,
        din8_WIDTH => 16,
        din9_WIDTH => 16,
        din10_WIDTH => 16,
        din11_WIDTH => 16,
        din12_WIDTH => 16,
        din13_WIDTH => 4,
        dout_WIDTH => 16)
    port map (
        din0 => tmp_data_V_0,
        din1 => tmp_data_V_1,
        din2 => tmp_data_V_2,
        din3 => tmp_data_V_3,
        din4 => tmp_data_V_4,
        din5 => tmp_data_V_5,
        din6 => tmp_data_V_6,
        din7 => tmp_data_V_727,
        din8 => tmp_data_V_8,
        din9 => tmp_data_V_9,
        din10 => tmp_data_V_10,
        din11 => tmp_data_V_11,
        din12 => tmp_data_V_12,
        din13 => j3_0_i_reg_218,
        dout => tmp_V_3_fu_252_p15);

    myproject_axi_lshr_32ns_32ns_32_2_1_U1194 : component myproject_axi_lshr_32ns_32ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        OP => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_467_p0,
        din1 => add_ln958_reg_664,
        ce => ap_const_logic_1,
        dout => grp_fu_467_p2);

    myproject_axi_shl_64ns_32ns_64_2_1_U1195 : component myproject_axi_shl_64ns_32ns_64_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        OP => 0,
        din0_WIDTH => 64,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_475_p0,
        din1 => grp_fu_475_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_475_p2);

    regslice_both_out_data_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => out_r_TDATA_int,
        vld_in => out_r_TVALID_int,
        ack_in => out_r_TREADY_int,
        data_out => out_r_TDATA,
        vld_out => regslice_both_out_data_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_data_U_apdone_blk);

    regslice_both_out_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => last_reg_585,
        vld_in => out_r_TVALID_int,
        ack_in => regslice_both_out_last_V_U_ack_in_dummy,
        data_out => out_r_TLAST,
        vld_out => regslice_both_out_last_V_U_vld_out,
        ack_out => out_r_TREADY,
        apdone_blk => regslice_both_out_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln31_fu_229_p2 = ap_const_lv1_1) and (regslice_both_out_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    j3_0_i_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_r_TREADY_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                j3_0_i_reg_218 <= j_reg_580;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j3_0_i_reg_218 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln935_reg_608 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                add_ln958_reg_664 <= add_ln958_fu_391_p2;
                icmp_ln947_1_reg_659 <= icmp_ln947_1_fu_385_p2;
                lsb_index_reg_648 <= lsb_index_fu_356_p2;
                sub_ln958_reg_669 <= sub_ln958_fu_396_p2;
                tmp_reg_654 <= lsb_index_fu_356_p2(31 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln935_reg_608 <= icmp_ln935_fu_297_p2;
                l_reg_621 <= l_fu_325_p3;
                tmp_V_4_reg_613 <= tmp_V_4_fu_302_p3;
                trunc_ln943_reg_626 <= trunc_ln943_fu_333_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln935_reg_608 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                icmp_ln958_reg_689 <= icmp_ln958_fu_462_p2;
                    or_ln_i_reg_674(0) <= or_ln_i_fu_448_p3(0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((regslice_both_out_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                j_reg_580 <= j_fu_235_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_229_p2 = ap_const_lv1_0) and (regslice_both_out_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                last_reg_585 <= last_fu_247_p2;
                p_Result_39_reg_597 <= tmp_V_3_fu_252_p15(15 downto 15);
                tmp_V_3_reg_590 <= tmp_V_3_fu_252_p15;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln935_reg_608 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                lshr_ln958_reg_699 <= grp_fu_467_p2;
                shl_ln958_reg_704 <= grp_fu_475_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln935_reg_608 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                m_5_reg_709 <= m_2_fu_493_p2(63 downto 1);
                tmp_94_reg_714 <= m_2_fu_493_p2(25 downto 25);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln935_reg_608 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    select_ln964_reg_719(0) <= select_ln964_fu_517_p3(0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln935_reg_608 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                sub_ln944_reg_631 <= sub_ln944_fu_337_p2;
                sub_ln947_reg_643 <= sub_ln947_fu_350_p2;
                trunc_ln944_reg_638 <= trunc_ln944_fu_342_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((p_Result_39_reg_597 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_V_reg_603 <= tmp_V_fu_292_p2;
            end if;
        end if;
    end process;
    or_ln_i_reg_674(31 downto 1) <= "0000000000000000000000000000000";
    select_ln964_reg_719(7 downto 1) <= "0111111";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state2, regslice_both_out_data_U_apdone_blk, icmp_ln31_fu_229_p2, out_r_TREADY_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln31_fu_229_p2 = ap_const_lv1_1) and (regslice_both_out_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln31_fu_229_p2 = ap_const_lv1_0) and (regslice_both_out_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((out_r_TREADY_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((out_r_TREADY_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    a_fu_406_p2 <= (icmp_ln947_fu_401_p2 and icmp_ln947_1_reg_659);
    add_ln949_fu_424_p2 <= std_logic_vector(signed(ap_const_lv16_FFE8) + signed(trunc_ln944_reg_638));
    add_ln958_fu_391_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFE7) + signed(sub_ln944_reg_631));
    add_ln964_fu_532_p2 <= std_logic_vector(unsigned(sub_ln964_fu_527_p2) + unsigned(select_ln964_reg_719));
    and_ln949_fu_436_p2 <= (xor_ln949_fu_418_p2 and p_Result_37_fu_429_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, regslice_both_out_data_U_apdone_blk, icmp_ln31_fu_229_p2)
    begin
        if (((icmp_ln31_fu_229_p2 = ap_const_lv1_1) and (regslice_both_out_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, regslice_both_out_data_U_apdone_blk, icmp_ln31_fu_229_p2)
    begin
        if (((icmp_ln31_fu_229_p2 = ap_const_lv1_1) and (regslice_both_out_data_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln739_fu_560_p1 <= trunc_ln738_fu_556_p1;
    grp_fu_467_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_4_reg_613),32));
    grp_fu_475_p0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_V_4_reg_613),64));
    grp_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln958_reg_669),64));
    icmp_ln31_fu_229_p2 <= "1" when (j3_0_i_reg_218 = ap_const_lv4_D) else "0";
    icmp_ln32_fu_241_p2 <= "1" when (j3_0_i_reg_218 = ap_const_lv4_C) else "0";
    icmp_ln935_fu_297_p2 <= "1" when (tmp_V_3_reg_590 = ap_const_lv16_0) else "0";
    icmp_ln947_1_fu_385_p2 <= "0" when (p_Result_35_fu_380_p2 = ap_const_lv16_0) else "1";
    icmp_ln947_fu_401_p2 <= "1" when (signed(tmp_reg_654) > signed(ap_const_lv31_0)) else "0";
    icmp_ln958_fu_462_p2 <= "1" when (signed(lsb_index_reg_648) > signed(ap_const_lv32_0)) else "0";
    j_fu_235_p2 <= std_logic_vector(unsigned(j3_0_i_reg_218) + unsigned(ap_const_lv4_1));
    
    l_fu_325_p3_proc : process(p_Result_40_fu_317_p3)
    begin
        l_fu_325_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if p_Result_40_fu_317_p3(i) = '1' then
                l_fu_325_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    last_fu_247_p2 <= (p_read and icmp_ln32_fu_241_p2);
    lsb_index_fu_356_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFE8) + signed(sub_ln944_reg_631));
    lshr_ln947_fu_374_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv16_FFFF),to_integer(unsigned('0' & zext_ln947_fu_371_p1(16-1 downto 0)))));
    m_1_fu_484_p3 <= 
        zext_ln958_fu_481_p1 when (icmp_ln958_reg_689(0) = '1') else 
        shl_ln958_reg_704;
    m_2_fu_493_p2 <= std_logic_vector(unsigned(zext_ln961_fu_490_p1) + unsigned(m_1_fu_484_p3));
    m_6_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_5_reg_709),64));
    or_ln949_fu_442_p2 <= (and_ln949_fu_436_p2 or a_fu_406_p2);
    or_ln_i_fu_448_p3 <= (ap_const_lv31_0 & or_ln949_fu_442_p2);

    out_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12, out_r_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            out_r_TDATA_blk_n <= out_r_TREADY_int;
        else 
            out_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_TDATA_int <= 
        ap_const_lv32_0 when (icmp_ln935_reg_608(0) = '1') else 
        bitcast_ln739_fu_560_p1;
    out_r_TVALID <= regslice_both_out_data_U_vld_out;

    out_r_TVALID_int_assign_proc : process(ap_CS_fsm_state11, out_r_TREADY_int)
    begin
        if (((out_r_TREADY_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            out_r_TVALID_int <= ap_const_logic_1;
        else 
            out_r_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_35_fu_380_p2 <= (tmp_V_4_reg_613 and lshr_ln947_fu_374_p2);
    p_Result_37_fu_429_p3 <= tmp_V_4_reg_613(to_integer(unsigned(add_ln949_fu_424_p2)) downto to_integer(unsigned(add_ln949_fu_424_p2))) when (to_integer(unsigned(add_ln949_fu_424_p2))>= 0 and to_integer(unsigned(add_ln949_fu_424_p2))<=15) else "-";
    p_Result_40_fu_317_p3 <= (ap_const_lv16_FFFF & p_Result_s_fu_307_p4);
    p_Result_41_fu_544_p5 <= (m_6_fu_524_p1(63 downto 32) & tmp_93_i_fu_537_p3 & m_6_fu_524_p1(22 downto 0));
    
    p_Result_s_fu_307_p4_proc : process(tmp_V_4_fu_302_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(16+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable p_Result_s_fu_307_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(16 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_F(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_0(4 - 1 downto 0);
        v0_cpy := tmp_V_4_fu_302_p3;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_0(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(16-1-unsigned(ap_const_lv32_F(4-1 downto 0)));
            for p_Result_s_fu_307_p4_i in 0 to 16-1 loop
                v0_cpy(p_Result_s_fu_307_p4_i) := tmp_V_4_fu_302_p3(16-1-p_Result_s_fu_307_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(16-1 downto 0)))));
        res_mask := res_mask(16-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        p_Result_s_fu_307_p4 <= resvalue(16-1 downto 0);
    end process;

    select_ln964_fu_517_p3 <= 
        ap_const_lv8_7F when (tmp_94_reg_714(0) = '1') else 
        ap_const_lv8_7E;
    sub_ln944_fu_337_p2 <= std_logic_vector(unsigned(ap_const_lv32_10) - unsigned(l_reg_621));
    sub_ln947_fu_350_p2 <= std_logic_vector(unsigned(ap_const_lv5_9) - unsigned(trunc_ln947_fu_346_p1));
    sub_ln958_fu_396_p2 <= std_logic_vector(unsigned(ap_const_lv32_19) - unsigned(sub_ln944_reg_631));
    sub_ln964_fu_527_p2 <= std_logic_vector(unsigned(ap_const_lv8_6) - unsigned(trunc_ln943_reg_626));
    tmp_93_fu_411_p3 <= lsb_index_reg_648(31 downto 31);
    tmp_93_i_fu_537_p3 <= (p_Result_39_reg_597 & add_ln964_fu_532_p2);
    tmp_V_4_fu_302_p3 <= 
        tmp_V_reg_603 when (p_Result_39_reg_597(0) = '1') else 
        tmp_V_3_reg_590;
    tmp_V_fu_292_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_V_3_reg_590));
    trunc_ln738_fu_556_p1 <= p_Result_41_fu_544_p5(32 - 1 downto 0);
    trunc_ln943_fu_333_p1 <= l_fu_325_p3(8 - 1 downto 0);
    trunc_ln944_fu_342_p1 <= sub_ln944_fu_337_p2(16 - 1 downto 0);
    trunc_ln947_fu_346_p1 <= sub_ln944_fu_337_p2(5 - 1 downto 0);
    xor_ln949_fu_418_p2 <= (tmp_93_fu_411_p3 xor ap_const_lv1_1);
    zext_ln947_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln947_reg_643),16));
    zext_ln958_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln958_reg_699),64));
    zext_ln961_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_i_reg_674),64));
end behav;
