// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_HH_
#define _reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_axi_mux_104_18_1_1.h"

namespace ap_rtl {

struct reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<17> > x_0_V;
    sc_in< sc_lv<17> > x_1_V;
    sc_in< sc_lv<17> > x_2_V;
    sc_in< sc_lv<17> > x_3_V;
    sc_in< sc_lv<17> > x_4_V;
    sc_in< sc_lv<17> > x_5_V;
    sc_in< sc_lv<17> > x_6_V;
    sc_in< sc_lv<17> > x_7_V;
    sc_in< sc_lv<17> > x_8_V;
    sc_in< sc_lv<17> > x_9_V;
    sc_in< sc_lv<5> > x_V_offset;
    sc_out< sc_lv<18> > ap_return;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s(sc_module_name name);
    SC_HAS_PROCESS(reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s);

    ~reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s();

    sc_trace_file* mVcdFile;

    myproject_axi_mux_104_18_1_1<1,1,18,18,18,18,18,18,18,18,18,18,4,18>* myproject_axi_mux_104_18_1_1_U1910;
    myproject_axi_mux_104_18_1_1<1,1,18,18,18,18,18,18,18,18,18,18,4,18>* myproject_axi_mux_104_18_1_1_U1911;
    myproject_axi_mux_104_18_1_1<1,1,18,18,18,18,18,18,18,18,18,18,4,18>* myproject_axi_mux_104_18_1_1_U1912;
    myproject_axi_mux_104_18_1_1<1,1,18,18,18,18,18,18,18,18,18,18,4,18>* myproject_axi_mux_104_18_1_1_U1913;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > trunc_ln36_fu_118_p1;
    sc_signal< sc_lv<4> > trunc_ln36_reg_562;
    sc_signal< sc_lv<3> > add_ln43_fu_122_p2;
    sc_signal< sc_lv<3> > add_ln43_reg_567;
    sc_signal< sc_lv<3> > add_ln45_fu_128_p2;
    sc_signal< sc_lv<3> > add_ln45_reg_572;
    sc_signal< sc_lv<3> > add_ln43_1_fu_134_p2;
    sc_signal< sc_lv<3> > add_ln43_1_reg_577;
    sc_signal< sc_lv<17> > ap_port_reg_x_0_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_1_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_2_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_3_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_4_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_5_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_6_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_7_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_8_V;
    sc_signal< sc_lv<17> > ap_port_reg_x_9_V;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<3> > empty_fu_114_p1;
    sc_signal< sc_lv<18> > zext_ln43_fu_140_p1;
    sc_signal< sc_lv<18> > zext_ln43_2_fu_144_p1;
    sc_signal< sc_lv<18> > zext_ln43_3_fu_148_p1;
    sc_signal< sc_lv<18> > zext_ln43_4_fu_152_p1;
    sc_signal< sc_lv<18> > zext_ln43_5_fu_156_p1;
    sc_signal< sc_lv<18> > zext_ln43_6_fu_160_p1;
    sc_signal< sc_lv<18> > zext_ln43_7_fu_164_p1;
    sc_signal< sc_lv<18> > zext_ln43_8_fu_168_p1;
    sc_signal< sc_lv<18> > zext_ln43_9_fu_172_p1;
    sc_signal< sc_lv<18> > zext_ln43_10_fu_176_p1;
    sc_signal< sc_lv<4> > p_Val2_32_fu_208_p11;
    sc_signal< sc_lv<18> > p_Val2_s_fu_180_p12;
    sc_signal< sc_lv<18> > p_Val2_32_fu_208_p12;
    sc_signal< sc_lv<19> > rhs_V_2_fu_238_p1;
    sc_signal< sc_lv<19> > lhs_V_2_fu_234_p1;
    sc_signal< sc_lv<19> > ret_V_fu_242_p2;
    sc_signal< sc_lv<18> > p_Val2_34_fu_256_p2;
    sc_signal< sc_lv<1> > p_Result_22_fu_262_p3;
    sc_signal< sc_lv<1> > p_Result_s_fu_248_p3;
    sc_signal< sc_lv<1> > xor_ln786_12_fu_270_p2;
    sc_signal< sc_lv<1> > xor_ln340_25_fu_288_p2;
    sc_signal< sc_lv<1> > xor_ln340_24_fu_282_p2;
    sc_signal< sc_lv<1> > underflow_fu_276_p2;
    sc_signal< sc_lv<1> > or_ln340_12_fu_294_p2;
    sc_signal< sc_lv<18> > select_ln340_128_fu_300_p3;
    sc_signal< sc_lv<18> > select_ln388_12_fu_308_p3;
    sc_signal< sc_lv<4> > p_Val2_35_fu_327_p11;
    sc_signal< sc_lv<4> > p_Val2_2_fu_356_p11;
    sc_signal< sc_lv<18> > p_Val2_35_fu_327_p12;
    sc_signal< sc_lv<18> > p_Val2_2_fu_356_p12;
    sc_signal< sc_lv<19> > rhs_V_3_fu_386_p1;
    sc_signal< sc_lv<19> > lhs_V_3_fu_382_p1;
    sc_signal< sc_lv<19> > ret_V_2_fu_390_p2;
    sc_signal< sc_lv<18> > p_Val2_37_fu_404_p2;
    sc_signal< sc_lv<1> > p_Result_24_fu_410_p3;
    sc_signal< sc_lv<1> > p_Result_23_fu_396_p3;
    sc_signal< sc_lv<1> > xor_ln786_13_fu_418_p2;
    sc_signal< sc_lv<1> > xor_ln340_27_fu_436_p2;
    sc_signal< sc_lv<1> > xor_ln340_26_fu_430_p2;
    sc_signal< sc_lv<1> > underflow_2_fu_424_p2;
    sc_signal< sc_lv<1> > or_ln340_13_fu_442_p2;
    sc_signal< sc_lv<18> > select_ln340_130_fu_448_p3;
    sc_signal< sc_lv<18> > select_ln388_13_fu_456_p3;
    sc_signal< sc_lv<18> > p_Val2_38_fu_316_p3;
    sc_signal< sc_lv<18> > p_Val2_39_fu_464_p3;
    sc_signal< sc_lv<19> > lhs_V_fu_472_p1;
    sc_signal< sc_lv<19> > rhs_V_fu_476_p1;
    sc_signal< sc_lv<19> > ret_V_3_fu_480_p2;
    sc_signal< sc_lv<18> > p_Val2_41_fu_494_p2;
    sc_signal< sc_lv<1> > p_Result_26_fu_500_p3;
    sc_signal< sc_lv<1> > p_Result_25_fu_486_p3;
    sc_signal< sc_lv<1> > xor_ln786_fu_508_p2;
    sc_signal< sc_lv<1> > xor_ln340_fu_526_p2;
    sc_signal< sc_lv<1> > xor_ln340_28_fu_520_p2;
    sc_signal< sc_lv<1> > underflow_3_fu_514_p2;
    sc_signal< sc_lv<1> > or_ln340_fu_532_p2;
    sc_signal< sc_lv<18> > select_ln340_fu_538_p3;
    sc_signal< sc_lv<18> > select_ln388_fu_546_p3;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<3> ap_const_lv3_2;
    static const sc_lv<3> ap_const_lv3_3;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<18> ap_const_lv18_1FFFF;
    static const sc_lv<18> ap_const_lv18_20000;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln43_1_fu_134_p2();
    void thread_add_ln43_fu_122_p2();
    void thread_add_ln45_fu_128_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_empty_fu_114_p1();
    void thread_lhs_V_2_fu_234_p1();
    void thread_lhs_V_3_fu_382_p1();
    void thread_lhs_V_fu_472_p1();
    void thread_or_ln340_12_fu_294_p2();
    void thread_or_ln340_13_fu_442_p2();
    void thread_or_ln340_fu_532_p2();
    void thread_p_Result_22_fu_262_p3();
    void thread_p_Result_23_fu_396_p3();
    void thread_p_Result_24_fu_410_p3();
    void thread_p_Result_25_fu_486_p3();
    void thread_p_Result_26_fu_500_p3();
    void thread_p_Result_s_fu_248_p3();
    void thread_p_Val2_2_fu_356_p11();
    void thread_p_Val2_32_fu_208_p11();
    void thread_p_Val2_34_fu_256_p2();
    void thread_p_Val2_35_fu_327_p11();
    void thread_p_Val2_37_fu_404_p2();
    void thread_p_Val2_38_fu_316_p3();
    void thread_p_Val2_39_fu_464_p3();
    void thread_p_Val2_41_fu_494_p2();
    void thread_ret_V_2_fu_390_p2();
    void thread_ret_V_3_fu_480_p2();
    void thread_ret_V_fu_242_p2();
    void thread_rhs_V_2_fu_238_p1();
    void thread_rhs_V_3_fu_386_p1();
    void thread_rhs_V_fu_476_p1();
    void thread_select_ln340_128_fu_300_p3();
    void thread_select_ln340_130_fu_448_p3();
    void thread_select_ln340_fu_538_p3();
    void thread_select_ln388_12_fu_308_p3();
    void thread_select_ln388_13_fu_456_p3();
    void thread_select_ln388_fu_546_p3();
    void thread_trunc_ln36_fu_118_p1();
    void thread_underflow_2_fu_424_p2();
    void thread_underflow_3_fu_514_p2();
    void thread_underflow_fu_276_p2();
    void thread_xor_ln340_24_fu_282_p2();
    void thread_xor_ln340_25_fu_288_p2();
    void thread_xor_ln340_26_fu_430_p2();
    void thread_xor_ln340_27_fu_436_p2();
    void thread_xor_ln340_28_fu_520_p2();
    void thread_xor_ln340_fu_526_p2();
    void thread_xor_ln786_12_fu_270_p2();
    void thread_xor_ln786_13_fu_418_p2();
    void thread_xor_ln786_fu_508_p2();
    void thread_zext_ln43_10_fu_176_p1();
    void thread_zext_ln43_2_fu_144_p1();
    void thread_zext_ln43_3_fu_148_p1();
    void thread_zext_ln43_4_fu_152_p1();
    void thread_zext_ln43_5_fu_156_p1();
    void thread_zext_ln43_6_fu_160_p1();
    void thread_zext_ln43_7_fu_164_p1();
    void thread_zext_ln43_8_fu_168_p1();
    void thread_zext_ln43_9_fu_172_p1();
    void thread_zext_ln43_fu_140_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
