Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    conv1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv2_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    flatten:
      Precision:
        result: fixed<16,6>
      Trace: false
    maxpool1:
      Precision:
        result: fixed<16,6>
      Trace: false
    maxpool2:
      Precision:
        result: fixed<16,6>
      Trace: false
    output:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    output_softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'projects/ptq_hls4ml_prj/keras_model.h5'
OutputDir: projects/ptq_hls4ml_prj
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 9D7a7a6B
Version: 1.0.0
